### ISSUE TITLE
Save latest output selected and reopen it when available

### ISSUE THREAD

**Issue by Llorx** [keijiro/Nsm#13]
I just compiled it for Android. Works like a charm. Just the feature needed without any more paraphernalia. I just miss a feature, when I open the app, I would like it to reopen the last selected source when it is available, like official Studio Monitor does.

I just have an Android TV and want to open a very specific NDI stream when I turn on that TV.

Thank you for this tool.

**Comment by keijiro** [comment]
That's nice to add. I'll think about it in future updates.

**Comment by Llorx** [comment]
Just created a PR: https://github.com/keijiro/Nsm/pull/14

**Comment by REDDDDY** [comment]
can you please make NDI HX source monitor for android?

**Comment by keijiro** [comment]
@REDDDDY That's off-topic. Please create a new issue for a new topic.

**Comment by keijiro** [comment]
This feature is implemented in the latest version.
