### ISSUE TITLE
Can an APK be provided?

### ISSUE THREAD

**Issue by tigert10** [keijiro/Nsm#16]
Hi, I am wondering if an Android APK can be provided for download? I'd love to try this but do not have the knowledge to compile the APK myself. Any help would be greatly appreciated. Thanks!

**Comment by keijiro** [comment]
> I am wondering if an Android APK can be provided for download? 

No.

Now I'm thinking of adding it in the next release.

**Comment by keijiro** [comment]
I'm closing this issue now. Please reopen it for further problems.
