### ISSUE TITLE
Feature Addition Request

### ISSUE THREAD

**Issue by wongdi** [keijiro/Nsm#19]
Hello
The Android version of this tool is so impressive to me that I would like to ask the author to add two useful features to it.
1. Audio support for NDI 5
2. Bandwidth display for NDI

thk☺

**Comment by keijiro** [comment]
> Audio support for NDI 5

Unfortunately, the KlakNDI plugin doesn't support audio. This limitation came from Unity's audio system.

> Bandwidth display for NDI

This should be controlled by NDI senders.
