### ISSUE TITLE
Android to Android not working 

### ISSUE THREAD

**Issue by TidusWulf** [keijiro/Nsm#23]
![Screenshot_20230112-080114](https://user-images.githubusercontent.com/29513712/212231116-fb2d17ac-42cd-461c-9118-6555bd0113fe.png)
Compiled with unity, installed Nsm to a pixel 7 (unlocked) with latest Android OS. source device was a Samsung Galaxy s9+, I believe with Android 10 or 11, whatever is newest.

I suspect the problem is that on Android, the official ndi app is NDI HX. Screen capture NDI on Windows shows up fine in NSM compiled for Android. It's only Android to Android that is broken.

**Comment by keijiro** [comment]
My understanding is that the NDI SDK (standard version) doesn't support NDI HX.

**Comment by TidusWulf** [comment]
Bummer. Thank you for the quick response.
