### ISSUE TITLE
New request : NDI HX source monitor for android

### ISSUE THREAD

**Issue by REDDDDY** [keijiro/Nsm#24]
can you please make NDI HX source monitor for android?
Currently there are no official mobile app for NDIHX source monitor except for iOS platform developed by Sienna.
It would be really great if there is an app for this on Android.

**Comment by keijiro** [comment]
The public NDI SDK doesn't support NDI HX. Sadly, it requires tons of money.

**Comment by keijiro** [comment]
I close this issue as technically impossible. Please open it for further issues.
