### ISSUE TITLE
Specify NDI Source From Command Line

### ISSUE THREAD

**Issue by wtribe** [keijiro/Nsm#28]
Hello,

I've looked through the previous questions and don't see this. Sorry if I've missed it.

Running on Linux. Working well. Thanks!

Is there a way to specify the NDI source when launching Nsm? This would allow for unattended startup.

Thanks.

**Comment by keijiro** [comment]
There is no command line option at the moment. I think that's a nice-to-add feature.

**Comment by laserpanda** [comment]
cant see a way to star this issue, so just adding a comment that this functionality would be appreciated

**Comment by keijiro** [comment]
This feature is implemented in 2.1.0.
