### ISSUE TITLE
Android app permission issue

### ISSUE THREAD

**Issue by newemka** [keijiro/Nsm#29]
Phone model: Samsung Galaxy S10e 
Software: Android 12

Hello! 
NSM is working well in Unity, I can select and see the NDI feeds. 

But when I build and run the apk on the phone I get a black screen and no UI.

If I turn on Development build I get this content error message :
![image](https://github.com/user-attachments/assets/caed70d1-37da-40ab-b442-35a86b5cb210)

AndroidJavaException:
java.lang.SecurityException: WifiService:
Neither user 10031 nor current process has android.permission.CHANGE_WIFI_MULTICAST_STATE.

Sorry, I can't figure out how to solve this issue. 
I will keep investigating.

**Comment by keijiro** [comment]
Could you try following the steps written in the "Android Support" section below?

https://github.com/keijiro/KlakNDI

**Comment by newemka** [comment]
Awesome! It works! Thank you so much!
 
I activated "Custom Main Manifest" 
Then I added the uses-permission code lines to AndroidManifest.xml

`<?xml version="1.0" encoding="utf-8"?>
<manifest
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">
  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <uses-permission android:name="android.permission.CHANGE_WIFI_MULTICAST_STATE" />
    <application>
        <activity android:name="com.unity3d.player.UnityPlayerActivity"
                  android:theme="@style/UnityThemeSelector">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <meta-data android:name="unityplayer.UnityActivity" android:value="true" />
        </activity>       
    </application>
</manifest>`

**Comment by keijiro** [comment]
Updated in the latest commit.
