### ISSUE TITLE
[ARM64] Can I compile this for an ARM64 (Odroid C4 / C2) platform?

### ISSUE THREAD

**Issue by MDAR** [keijiro/Nsm#4]
Hi

I'm looking for a farly simple way to view a NDI stream at full screen on an ARM64 platform.

The use case is that we have a number of SDi cameras coming into our Atem desk, but we would like to add a couple (*maybe just one) NDI based camera as an extra.

What we currently have is an Odroid C2 or C4 generating adhoc overlay content, which is ChromaKeyed into the mix.

If I could get the same box to to convert an NDI stream into a 1920 x 1080 HDMI output, we could use it on the Atem.

A. Can I compile your app on a ARM64 system?

B. Is there anyway to push settings into it via the command line, instead of a UI on screen?

For example, can we start the APP with a command line flag that pre-selects the source?
or
Is there a websocket / TCP port that could be used to select the source?

I'm happy  to go into more detail if it helps.

I'm also happy to accept "No" as an answer.

Happy new year

**Comment by esaeberg** [comment]
Hi
I could be interested to the same thing for connect a projector to a ndi system. For now we use a birddog box but it’s expensive and we want to use it for other thing.
So hope they will be an answer soon

**Comment by OscarParzon** [comment]
Hello, also interested in ARM (Odroid XU4, RPi 4, etc.). It's possible ?.
Doubt: Can it be used in INTEL NUC ???

Thanks. Thank you very much for your effort.

**Comment by rlpalov** [comment]
Dear keijiro,

Hello, first thank you very much for your great projects!!! I am a fan, seems every time i look for a capability I find you are the developer who has made a solution!!

I also would love a simple NDI fullscreen HDMI out for small linux computer… looking at Jetson Nano 2GB quad-core ARM A57 64-bit CPU (Vulkan ✔︎).  Now that NDI 5 is out would Nsm player on ARM work ….  if I use v1.0.1 and install the NDI 5 advanced SDK  ...   would it be that simple??


Thank you

**Comment by keijiro** [comment]
Unity only supports x86-64 Linux. It's not technically possible to support ARM Linux systems.

The only exception is Android. Unity supports arm64 Android systems. So, if you can install Android to your device, it's possibly able to run Nsm.

I have never tried such a tricky installation. I'm not sure if it's a practical idea.
